apiVersion: v1
kind: Service
metadata:
  name: control-plane
  namespace: nanofaas
spec:
  selector:
    app: nanofaas-control-plane
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: actuator
      port: 8081
      targetPort: 8081
