apiVersion: batch/v1
kind: Job
metadata:
  generateName: fn-example-
  namespace: nanofaas
  labels:
    app: nanofaas
    function: example
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: function
          image: nanofaas/function-runtime:0.5.0
          env:
            - name: FUNCTION_NAME
              value: example
            - name: EXECUTION_ID
              value: example-execution
            - name: CALLBACK_URL
              value: http://control-plane.nanofaas.svc.cluster.local:8080/v1/internal/executions
