apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.controlPlane.service.name | quote }}
  namespace: {{ include "nanofaas.namespace" . | quote }}
spec:
  type: {{ .Values.controlPlane.service.type }}
  selector:
    {{- include "nanofaas.controlPlane.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.controlPlane.service.ports.http }}
      targetPort: {{ .Values.controlPlane.service.ports.http }}
    - name: actuator
      port: {{ .Values.controlPlane.service.ports.actuator }}
      targetPort: {{ .Values.controlPlane.service.ports.actuator }}
