{{- $legacyKubeletResourceMetricsEnabled := .Values.prometheus.kubeletResourceMetrics.enabled -}}
{{- $containerMetricsMode := default "kubelet" .Values.prometheus.containerMetrics.mode -}}
{{- $containerMetricsKubeletEnabled := or $legacyKubeletResourceMetricsEnabled (and .Values.prometheus.containerMetrics.enabled (eq $containerMetricsMode "kubelet")) -}}
{{- if and .Values.prometheus.create .Values.prometheus.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nanofaas-prometheus
  namespace: {{ include "nanofaas.namespace" . | quote }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nanofaas-prometheus
  namespace: {{ include "nanofaas.namespace" . | quote }}
subjects:
  - kind: ServiceAccount
    name: nanofaas-prometheus
    namespace: {{ include "nanofaas.namespace" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nanofaas-prometheus
{{- end -}}

{{- if and .Values.prometheus.create .Values.prometheus.rbac.create $containerMetricsKubeletEnabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nanofaas-prometheus-kubelet
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nanofaas-prometheus-kubelet
subjects:
  - kind: ServiceAccount
    name: nanofaas-prometheus
    namespace: {{ include "nanofaas.namespace" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nanofaas-prometheus-kubelet
{{- end -}}
