{{- if and .Values.prometheus.create .Values.prometheus.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nanofaas-prometheus
  namespace: {{ include "nanofaas.namespace" . | quote }}
{{- end -}}

