{{- if .Values.prometheus.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.service.name | quote }}
  namespace: {{ include "nanofaas.namespace" . | quote }}
  labels:
    app: nanofaas-prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: nanofaas-prometheus
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
      {{- if and (eq .Values.prometheus.service.type "NodePort") .Values.prometheus.service.nodePort }}
      nodePort: {{ .Values.prometheus.service.nodePort }}
      {{- end }}
{{- end -}}

