{{- if .Values.prometheus.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanofaas-prometheus
  namespace: {{ include "nanofaas.namespace" . | quote }}
  labels:
    app: nanofaas-prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nanofaas-prometheus
  template:
    metadata:
      labels:
        app: nanofaas-prometheus
      annotations:
        checksum/prometheus-config: {{ include (print $.Template.BasePath "/prometheus-configmap.yaml") . | sha256sum | quote }}
    spec:
      {{- if .Values.prometheus.rbac.create }}
      serviceAccountName: nanofaas-prometheus
      {{- end }}
      containers:
        - name: prometheus
          image: {{ .Values.prometheus.image | quote }}
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time={{ .Values.prometheus.retention }}"
          ports:
            - name: http
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: nanofaas-prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
              - key: rules.yml
                path: rules.yml
        - name: data
          {{- if .Values.prometheus.pvc.enabled }}
          persistentVolumeClaim:
            claimName: nanofaas-prometheus-data
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end -}}

